.TH "TEXTWIDTH" 1 "Jan 01 2008"
.SH NAME
textwidth \- calculate the width in pixels of text for a given font.
.SH SYNOPSIS
.HP 7
\fBtextwidth\fR  \fIfontname\fR \fIstring\fR
.SH DESCRIPTION
.B textwidth
is a simple utility to calculate the width in pixels of text with a given font.
.PP
This tool is provided as part of the
.B dzen2 (1)
package.
.SH OPTIONS
A summary of options is included below.
.TP
.B fontname
Set the font.
.TP
.B string
Set the string. 
.SH AUTHOR
.B textwidth
was written by Robert Manea.
.PP
This manual page was written by bertagaz <bertagaz@ptitcanardnoir.org>,
for the Debian project (but may be used by others).
.SH SEE ALSO
.BR dzen2 (1),
.BR dbar (1),
.BR gcpubar (1),
and
.BR gdbar (1).
